#!/bin/bash
# Generate Ansible inventory from Terraform outputs

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TERRAFORM_DIR="$SCRIPT_DIR/../terraform/env/prod"
INVENTORY_FILE="$SCRIPT_DIR/../ansible/inventory/hosts.ini"

echo "Generating Ansible inventory from Terraform outputs..."

cd "$TERRAFORM_DIR"

# Check if terraform has been applied
if ! terraform output -json > /dev/null 2>&1; then
    echo "Error: Terraform has not been applied yet. Run 'terraform apply' first."
    exit 1
fi

# Get Terraform outputs as JSON
OUTPUT=$(terraform output -json ansible_inventory)

# Parse outputs
SSH_USER=$(echo "$OUTPUT" | jq -r '.ssh_user')

# Start building inventory file
cat > "$INVENTORY_FILE" << 'EOF'
# Kubernetes Cluster Inventory
# Generated by generate-inventory.sh

EOF

# Add control plane nodes
echo "[control_plane]" >> "$INVENTORY_FILE"
echo "$OUTPUT" | jq -r '.control_plane[] | "cp\(.name | split("-") | last) ansible_host=\(.public_ip) private_ip=\(.private_ip)"' >> "$INVENTORY_FILE"

# Add worker nodes
echo "" >> "$INVENTORY_FILE"
echo "[workers]" >> "$INVENTORY_FILE"
echo "$OUTPUT" | jq -r '.workers[] | "worker\(.name | split("-") | last) ansible_host=\(.public_ip) private_ip=\(.private_ip)"' >> "$INVENTORY_FILE"

# Add group children
cat >> "$INVENTORY_FILE" << 'EOF'

[k8s_cluster:children]
control_plane
workers

[primary_control_plane]
cp1
EOF

echo "Inventory generated successfully at $INVENTORY_FILE"
echo ""
echo "Contents:"
cat "$INVENTORY_FILE"
